
image:
  file: .gitpod.dockerfile
ports:
  - port: 19000-19002
tasks:
  - before: npm install
    command: expo login -u zizwar -p @12345666 && expo start --tunnel
vscode:
  extensions:
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==
