
image:
  file: .gitpod.dockerfile
ports:
  - port: 19000-19002
tasks:
  - name: introFlodeExempleExpo
    command: bash -lc "cd exemple && npm i && expo login -u zizwar -p @12345666 && expo start --tunnel"
vscode:
  extensions:
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==
